# Generated by Django 4.0 on 2021-12-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=50)),
                ('num_subgeneros', models.IntegerField()),
                ('genero_activo', models.BooleanField()),
                ('genero_ganancias', models.FloatField()),
            ],
        ),
    ]
