# Generated by Django 4.0 on 2021-12-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudEntidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=50)),
                ('pelicula_ganancias', models.FloatField()),
                ('pelicula_en_cartelera', models.BooleanField()),
                ('pelicula_director', models.CharField(max_length=50)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudEntidades.genero')),
            ],
        ),
    ]
